services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DATABASEURL=mongodb://mongo:27017/ems
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - CI=false
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongo_data:


